### ISSUE TITLE
No MYMETA files in dist tar ball

### ISSUE THREAD

**Issue by tokuhirom** [Scalar-List-Utils/Scalar-List-Utils#14]
You shouldn't include MYMETA.json, MYMEATA.yml in your distribution.

ref.
- http://api.metacpan.org/source/PEVANS/Scalar-List-Utils-1.38/
- http://cpants.cpanauthors.org/dist/Scalar-List-Utils-1.38

**Comment by leonerd** [comment]
Resolved by 829b895
